export const toolsData = [
  {
    id: 1,
    title: "CodeAssist AI",
    description: "CodeAssist AI helps developers write, debug, and optimize code. CodeAssist AI can provide real-time code completions and suggestions, helping developers write code faster and avoid mistakes. It can automatically suggest reusable code snippets for common tasks, eliminating the need to write boilerplate code from scratch. AI can help identify the root causes of bugs or performance issues by analyzing code patterns and execution flows.",
    price: 49.99,
    category: "Development",
    image: "https://chriskirby.net/content/images/2024/02/AICodingAssistant.png",
    rating: { rate: 4.7, count: 320 },
  },
  {
    id: 2,
    title: "DataViz Pro",
    description: "DataViz Pro makes it easier to understand large, complex datasets by turning raw numbers into visual formats like charts, graphs, and maps. This helps users quickly identify trends, patterns, and anomalies. Transforms raw data into interactive charts and dashboards. With advanced visualizations, users can spot insights in seconds—whether it's a spike in sales, a geographical trend, or a seasonal pattern—without needing to dive into raw data.",
    price: 59.99,
    category: "Analytics",
    image: "https://images.ctfassets.net/p80c52b4itd3/4wxtxpu0KW2FN0Ksl4hTvQ/e7768a09cb64c3beebe1488c1973d36f/Pro_Tips_Visualization.png",
    rating: { rate: 4.6, count: 210 },
  },
  {
    id: 3,
    title: "ContentGenius",
    description: "ContentGenius can generate high-quality text quickly, saving time and effort for content creators. It can be used for blog posts, social media updates, newsletters, product descriptions, and more. Generates high-quality marketing copy and blogs. Automation helps maintain a consistent output of content without sacrificing quality, ensuring that content is produced at scale. ContentGenius can optimize content for search engines by recommending keyword usage, meta descriptions, and header tags, which increases the likelihood of ranking higher in search results.",
    price: 39.99,
    category: "Content",
    image: "https://st3.depositphotos.com/1001201/17776/i/450/depositphotos_177768496-stock-photo-bright-bulb-lit-between-unlit.jpg",
    rating: { rate: 4.8, count: 430 },
  },
  {
    id: 4,
    title: "SmartScheduler",
    description: "SmartScheduler automates the scheduling process, eliminating the need for back-and-forth emails or calls to find suitable meeting times. This makes scheduling quick and seamless. The tool automatically finds overlapping free time slots between participants and schedules meetings based on their availability. Optimizes your calendar and suggests meeting times. It allows users to set up recurring events or meetings, whether it’s daily, weekly, monthly, or at custom intervals, without having to schedule them manually each time.",
    price: 29.99,
    category: "Productivity",
    image: "https://i0.wp.com/cosmictouchblog.com/wp-content/uploads/2024/01/AI-SCHEDULING-ASSISTANT-2.png?fit=900%2C800&ssl=1",
    rating: { rate: 4.5, count: 150 },
  },
  {
    id: 5,
    title: "ImageCraft AI",
    description: "Generate and edit images with advanced AI models. Create high-quality images from simple text prompts. For example, typing “a futuristic city at night in cyberpunk style” can instantly generate a matching image. Remove, replace, or expand image areas using AI. Great for product photography, social posts, or correcting images. Automatically detect and remove unwanted objects or backgrounds from images with precision. Instantly change or blur backgrounds without needing Photoshop or advanced tools.",
    price: 44.99,
    category: "Creative",
    image: "https://www.smartone.com/rotation_banner/special_offer/english/AI_life_hacks/ai_kv_mob.jpg",
    rating: { rate: 4.9, count: 270 },
  },
  {
    id: 6,
    title: "VoiceBot Pro",
    description: "VoiceBot Pro works around the clock, handling customer inquiries even outside of business hours. Conversational AI assistant for customer service. Accurately understands user intent even with different accents, speeds, or noise conditions. Handles context, memory, and follow-up questions for more natural and human-like interactions. Handles context, memory, and follow-up questions for more natural and human-like interactions.",
    price: 54.99,
    category: "Communication",
    image: "https://justoborn.com/wp-content/uploads/2024/08/ai_assistants.jpg-300x300.jpeg",
    rating: { rate: 4.4, count: 180 },
  },
  {
    id: 7,
    title: "PredictAI",
    description: "PredictAI uses advanced algorithms (regression, time series models, neural networks, etc.) to forecast sales, demand, inventory, customer behavior, and more. Constantly learns and improves with new data, reducing the margin of error compared to manual or traditional forecasting methods. Business users can run complex predictive models without needing to write code. It automatically selects and optimizes the best predictive models based on your data. Machine learning platform for predictive analytics.",
    price: 69.99,
    category: "Analytics",
    image: "https://img.freepik.com/premium-photo/friendly-robot-assistant-helps-two-business-professionals-with-their-work_856795-97000.jpg?w=360",
    rating: { rate: 4.7, count: 260 },
  },
  {
    id: 8,
    title: "SecureGuard",
    description: "SecureGuard continuously monitors systems and networks to detect and respond to threats like malware, ransomware, phishing, and zero-day attacks in real time. Combines firewalls, antivirus, intrusion detection systems (IDS), and behavior-based monitoring for robust protection. Real-time AI-powered cybersecurity tool. Uses machine learning to predict potential vulnerabilities or attack patterns before they happen. Flexible deployment options allow you to protect cloud-native, hybrid, or traditional infrastructures.",
    price: 79.99,
    category: "Security",
    image: "https://img.favpng.com/7/7/12/computer-security-robot-information-security-stock-photography-png-favpng-up1UhgCS0kT7wQtMjDDGZjebJ.jpg",
    rating: { rate: 4.9, count: 340 },
  },
  {
    id: 9,
    title: "EduMentor",
    description: "EduMentor adjusts lessons and activities based on each student’s strengths, weaknesses, pace, and progress. Provides tailored exercises, quizzes, and resources to help students improve in specific areas. Educators can monitor entire classes or individual students, adjust lesson plans, and intervene when needed. Instantly grades assignments, quizzes, and even essays using AI, saving teachers hours of manual work. Personalized learning platform for students.",
    price: 34.99,
    category: "Education",
    image: "https://puremindsacademy.com/hubfs/AI-Generated%20Media/Images/Future%20classroom%20with%20a%20AI%20teacher%20with%20human%20students.jpeg",
    rating: { rate: 4.3, count: 120 },
  },
  {
    id: 10,
    title: "HealthAI",
    description: "HealthAI leverages advanced machine learning algorithms and vast medical datasets to assist doctors in diagnosing diseases with higher precision. By analyzing symptoms, medical history, imaging results, and lab reports, it helps reduce diagnostic errors, ensuring timely and accurate identification of conditions such as cancer, cardiovascular disease, diabetes, and rare illnesses that may be missed by the human eye alone. AI assistant for medical diagnosis and patient care.",
    price: 99.99,
    category: "Healthcare",
    image: "https://miro.medium.com/0*5eLtBHIztZV7ikwW",
    rating: { rate: 4.6, count: 190 },
  },
  {
    id: 11,
    title: "FinanceWise",
    description: "FinanceWise offers an all-in-one platform that allows users to manage their finances efficiently by consolidating budgeting, expense tracking, investment monitoring, and debt management in a single place. This holistic approach provides users with a clear, real-time overview of their financial health, empowering them to make informed decisions and avoid fragmented financial tracking across multiple apps or spreadsheets. AI-driven financial planning and investment advice.",
    price: 64.99,
    category: "Finance",
    image: "https://www.sphereinc.com/wp-content/uploads/2024/05/DALL%C2%B7E-2024-05-07-10.27.41-A-futuristic-and-abstract-representation-of-AI-in-finance-featuring-digital-symbols-like-algorithms-dollar-signs-graphs-and-data-streams-intertwin-1024x1024.webp",
    rating: { rate: 4.8, count: 210 },
  },
  {
    id: 12,
    title: "EcoTracker",
    description: "EcoTracker provides thorough and continuous monitoring of environmental parameters such as air and water quality, carbon emissions, energy consumption, and waste management. By gathering real-time data from multiple sources, it enables organizations and communities to gain a clear, accurate picture of their ecological impact. This holistic monitoring is essential for identifying pollution sources, tracking sustainability efforts, and ensuring compliance with environmental regulations. Tracks environmental impact and suggests sustainability improvements.",
    price: 42.99,
    category: "Environment",
    image: "https://img.freepik.com/premium-photo/futuristic-robot-tending-young-plant-symbolizing-sustainable-technology-environmental-care_856795-83090.jpg",
    rating: { rate: 4.5, count: 160 },
  },
];
